[versions]
agp = "8.10.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
material = "1.12.0"
constraintlayout = "2.2.1"
navigationFragment = "2.6.0"
navigationUi = "2.6.0"
sdpAndroid = "1.1.1"
sspAndroid = "1.1.1"
activity = "1.11.0"
activityVersion = "1.11.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigationUi" }
ssp-android = { module = "com.intuit.ssp:ssp-android", version.ref = "sspAndroid" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

